### ISSUE TITLE
Misaligned conversion to Vec<u8>: supported?

### ISSUE THREAD

**Issue by overminder** [myrrlyn/bitvec#10]
Hi, I've been using this crate for serial protocols and it worked great! Today I ran into an issue when trying to convert a misaligned `BitSlice` to a `Vec<u8>`:

```
use bitvec::bitvec;

let bv = bitvec![
    0, 0, 0, 0, 0, 0, 0, 1,
    1, 0, 0, 0, 0, 0, 0, 1,
];

let slice = &bv[4..12];
println!("bv[4..12] = {:?}", slice);
let bv2 = slice.to_owned();
println!("bv[4..12].to_owned() = {:?}", bv2);
let bs: Vec<u8> = bv2.into();
println!("bv[4..12].to_owned().into() = {:?}", bs);
```

which gives

```
bv[4..12] = BitSlice<BigEndian, u8> [0001, 1000]
bv[4..12].to_owned() = BitVec<BigEndian, u8> [0001, 1000]
bv[4..12].to_owned().into() = [1, 129]
```

Is this an intended behavior? I originally expected `bv[4..12]` to behave exactly like a regular aligned `BitSlice` (i.e., `bv[4..12].to_owned().into()` will just return an one element `Vec<u8>`)..

**Comment by myrrlyn** [comment]
Thanks for the report!

You are correct, this is not intended behavior. This is a result of premature optimization on my part in the implementation of `BitVec<C, T>::from_bitslice`. I had implemented it as cloning the underlying element slice, but the correct behavior is to collect the bits of the source bitslice into a new bitvector.

I have added the following test case,

```rust
let bv = bitvec![
	0, 0, 0, 0,
	0, 0, 0, 1,
	1, 0, 0, 0,
	0, 0, 0, 1,
];

let slice = &bv[4 .. 12];
assert_eq!(slice.len(), 8);
assert!(!slice[0]);
assert!(slice[3]);
assert!(slice[4]);
assert!(!slice[7]);

let bv2 = slice.to_owned();
assert_eq!(bv2, slice);
assert!(!bv2[0]);
assert!(bv2[3]);
assert!(bv2[4]);
assert!(!bv2[7]);
```

to demonstrate correct behavior.

**Comment by overminder** [comment]
That was super fast! Thanks for your fix :)

**Comment by myrrlyn** [comment]
I had to force-push an amended commit, make sure you're using 82563fe.
