### ISSUE TITLE
Build error in no_std environment

### ISSUE THREAD

**Issue by koushiro** [myrrlyn/bitvec#12]
https://github.com/myrrlyn/bitvec/blob/7e5fdc451879976acef1028f0b92b71f21eadd34/src/vec.rs#L3090

➜  bitvec git:(master) ✗ cargo build --no-default-features --features='alloc'
   Compiling bitvec v0.11.0 (/home/koushiro/Code/bitvec)
error: cannot find macro `eprintln!` in this scope
    --> src/vec.rs:3090:3
     |
3090 |         eprintln!("subtra: {}", subtrahend);
     |         ^^^^^^^^

error: aborting due to previous error

error: Could not compile `bitvec`.

**Comment by myrrlyn** [comment]
DANGIT I thought I got all those. You caught me; I'm bad at debugging.
