### ISSUE TITLE
Broken reference to the `body` function

### ISSUE THREAD

**Issue by DarkEld3r** [myrrlyn/bitvec#13]
> 	/// This is different from [`.body()`] in that it always includes the head
> 	/// and tail elements, even if they are partial.

https://github.com/myrrlyn/bitvec/blob/master/src/slice.rs#L1800
Perhaps this function has been removed?

**Comment by myrrlyn** [comment]
That function family was removed in 4cc10b6; forgot there were extant references. Thanks!
