### ISSUE TITLE
BitVec<LittleEndian, u64>::count_ones() result is off

### ISSUE THREAD

**Issue by mmstick** [myrrlyn/bitvec#14]
I'm attempting to use this as an alternative to the `cpu_set_t` affinity mask that the Linux kernel uses for getting and setting core affinities. The kernel operates on windows of `c_ulong` widths, so I have a 2048-bit wide `BitVec<LittleEndian, c_ulong>` to work with.

 I have a laptop with 8 virtual cores, so it correctly writes 8 bits when used with the `sched_getaffinity` syscall. However, the `Bits::count_ones` method only returns `2`, and printing the bitvec returns `11`, although printing and rendering the slice correctly shows 8 ones.

```rust
pub fn main() {
    let affinity = Process::current().get_affinity().unwrap();

    println!("ncpus: {}", affinity.count_ones());
    println!("{}", affinity);

    let slice: &[u64] = affinity.as_slice();
    println!("{:?}", slice);

    for elt in slice {
        println!("{:0w$b} ", elt, w = std::mem::size_of::<u64>() * 8);
    }
}
```
Output:
```
ncpus: 2
[11]
[255]
0000000000000000000000000000000000000000000000000000000011111111
```

**Comment by myrrlyn** [comment]
Thanks for the report! The bit counter methods are giving me no end of trouble.

Can you give me the output of `println!("{:?}", affinity.bitptr());`?

The *correct* output should look something like this:

```text
BitPtr<LittleEndian, u64> { 
  data: /* don't care */,
  elts: 32, // guessing from 2048 bits of u64?
  head: 0b000000,
  tail: 0b001000,
}
```

I'd also be interested in seeing how you are creating the `BitVec`; off the top of my head, those are all I can think of immediately for getting more information.

**Comment by mmstick** [comment]
Initialization occurs [here](https://github.com/pop-os/scheduler/blob/master/scheduler/src/scheduler/mod.rs#L15:L32).

```rust
let mut set = bitvec![LittleEndian, c_ulong; 0, 32];

let result = unsafe {
    let slice: &mut [c_ulong] = set.as_mut();
    libc::syscall(
        libc::SYS_sched_getaffinity,
        (*self).into(),
        mem::size_of::<c_ulong>(),
        slice.as_mut_ptr(),
    )
};
```

Output is

```rust
BitPtr<u64> {
    data: 0x0000562A2AE0CB40,
    elts: 0x1,
    head: 0b000000,
    tail: 0b000010
}
```

**Comment by myrrlyn** [comment]
Oh, your macro makes the vector have length 2, not 32. Use `0; 32` instead of `0, 32`.

That macro expands to:

```rust
{
  let mut bv = BitVec::<LittleEndian, c_ulong>::new();
  bv.push(0 != 0);
  bv.push(32 != 0);
  bv
}
```

You can also use `set_len` to explicitly tell the vector how many bits are live, or use `BitVec::from_element(&0)` to force the vector to span the entire unit.

**Comment by mmstick** [comment]
Thanks! That seems to work.

**Comment by myrrlyn** [comment]
Visually similar syntax is the bane of our existence; I'll update the docs to explicitly name the punctuation.
