### ISSUE TITLE
Incorrect `is_valid` check for `span` introduced in `0.11.2`

### ISSUE THREAD

**Issue by schomatis** [myrrlyn/bitvec#15]
See https://github.com/myrrlyn/bitvec/commit/ce4161297775a9bd3cbfdc5db1e2857cec202a64#diff-4c2d359d551a3a9316f813f4fd14f845R966.

Seems like it should be `is_valid_tail`. Already fixed in [`0.13`](https://github.com/myrrlyn/bitvec/commit/6a3482b1d6b582d3c24e8496f3f1d77cfaa4d215#diff-d477b91ecd9addc3f0a733d3ebd5d43fR972) but it would be nice to have it fixed in the `0.11.x` release as well (happy to submit a PR for it), thanks!

**Comment by myrrlyn** [comment]
`0.11.3` is on crates.io, and `0.11.2` has been yanked. Thanks for the note! That's what I get for tidying a bunch of work all at once.

**Comment by schomatis** [comment]
Thank you for the super fast support and for the work you've dedicated to this crate, it has saved me hours of developing time (and probably from more than one frustration too).
