### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by incker** [myrrlyn/bitvec#18]
fix please a little typo, I have an error:
`thread 'main' panicked at 'Index out of range: 32 >= 32',`
on code `*bits.at(32) = true;` where bits are from u32

**Comment by myrrlyn** [comment]
This is correct; the valid range in a `u32` is `0 ..= 31`; bit index `32` is out of bounds. This behavior was chosen to be consistent with Rust's zero-indexed array types; you will get the same behavior in `Vec`.

```rust
let v = vec![0; 8];
//  v has length 8, but does not have an index 8
assert!(v.get(8).is_none());
for n in 0 ..= 7 {
  assert!(v.get(n).is_some());
}
```
