### ISSUE TITLE
About changing Cursors

### ISSUE THREAD

**Issue by rubdos** [myrrlyn/bitvec#19]
Consider:

```rust
        use bitvec::prelude::*;
        let v = bitvec![1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0];
        assert_eq!(v.len(), 14);

        let s = &v.as_bitslice()[(v.len() - 8)..];
        assert_eq!(s.len(), 8);
        for i in 0..8 {
            assert_eq!(s[i], false);
        }

        let bitcount = s.count_ones();
        assert_eq!(0, bitcount);

        let s = s.change_cursor::<LittleEndian>();
        assert_eq!(s.len(), 8);

        let bitcount = s.count_ones();
        assert_eq!(0, bitcount);
        for i in 0..8 {
            assert_eq!(s[i], false);
        }
```

(EDIT: FYI, this crashes at the second bitcount assertion)

I would expect `s` to still be eight zeroes, but it gets bits outside the slice. That made me wonder about the semantics of the cursor: it iterates over *bytes* (`u8`'s) in some direction, but the notion of bytes is quite lost for `BitSlice`'s.

In any case:  I have a situation where I want to reverse every byte in a BitSlice that has size n*8...

**Comment by myrrlyn** [comment]
At present, the `change_cursors` method is a no-op, and is only used to alter types. As per your report, this is probably incorrect behavior in practice, but I'm not sure how to change it at this time.

Let's sketch out what is happening here:

```rust
use bitvec::prelude::*;
use std::iter;
let bv: BitVec<BigEndian, u8> =
  iter::repeat(true).take(6)
  .chain(iter::repeat(false).take(8));
```

`bv` governs the following memory:

```text
[ 1 1 1 1 1 1 0 0 ]
  0 1 2 3 4 5 6 7
[ 0 0 0 0 0 0 X X ]
  8 9 a b c d e f
```

Getting a subslice,

```rust
let bs: &BitSlice<BigEndian, u8> = &bv[6 ..];
```

causes the subslice to control the following memory:

```text
[ X X X X X X 0 0 ]
              0 1
[ 0 0 0 0 0 0 X X ]
  2 3 4 5 6 7
```

At present, the implementation of `.change_cursor` from `BigEndian` to `LittleEndian` will cause the slice to become this, instead:

```text
[ X X X X X X 0 0 ]
  1 0
[ 0 0 0 0 0 0 X X ]
      7 6 5 4 3 2
```

I strongly suspect it is impossible to express your desired memory layout (and, to be clear, the semantically correct one):

```text
[ X X X X X X 0 0 ]
              1 0
[ 0 0 0 0 0 0 X X ]
  7 6 5 4 3 2
```

in a `BitSlice` or `BitVec` instance.

----

I believe the most sure way to achieve your desired goal,

> I want to reverse every byte in a BitSlice that has size n*8...

as well as any general order change would be to perform an iteration/re-collection pass.

```rust
let rev = bv
  .iter()
  .collect::<BitVec<LittleEndian, u8>>();
```

This walks the original slice in the order I've described above, and then stores the iterated bits into the following memory layout:

```text
[ 0 0 1 1 1 1 1 1 ]
  7 6 5 4 3 2 1 0
[ X X 0 0 0 0 0 0 ]
      d c b a 9 8
```

Is this a useful solution to your problem? I will add a notice to the documentation that `change_cursors` causes this effect in semantic sets by changing how the underlying memory is interpreted, and that the iteration/collection process shown above is more likely to produce the intended results, especially on slices that do not fully span their memory elements.

**Comment by rubdos** [comment]
> Is this a useful solution to your problem?

Not really... I have to reverse every byte, but not the bytes themselves; which is what I think your suggestion does? I guess I'm in a pretty odd situation :-)

I've solved my particular problem by calling `swap` four times per byte on the mutable slice. Luckily for me, I don't really care about the performance here!
