### ISSUE TITLE
A NativeEndian cursor would be useful

### ISSUE THREAD

**Issue by glandium** [myrrlyn/bitvec#24]
In some cases, it is not interesting to deal with a specific endianness, and it would be more useful to use the native endianness whatever it is. One could import the right endianness depending on the target endianness, but it would be more convenient if there was a "NativeEndian" to avoid the manual gymnastic.

**Comment by myrrlyn** [comment]
I've spent all day trying to determine what a correct answer to this objectively reasonable question is. I've decided that `LittleEndian` is probably the more acceptable candidate to be considered "native" than is `BigEndian`, but both orders have pretty good reason to be used. Ultimately, the specific order doesn't matter for memory-only cases, and if you need to create an I/O buffer, you are already following a specification that forces you to pick one.

I am putting this article here for my records; you also may find it interesting: [*Reading bits in far too many ways, part 1](https://fgiesen.wordpress.com/2018/02/19/reading-bits-in-far-too-many-ways-part-1/).

At this time, I believe I have been convinced to switch the default `Cursor` to `LittleEndian`; I have not yet been persuaded to name either of them "`Native`", but I am weighing renaming both of them away from the term "endian", to be `MsbFirst` and `LsbFirst`.

----

Unfortunately I don't think I can add a `NativeEndian` name at this time; I will leave this issue open and keep thinking on it until I come to a firmer answer.

**Comment by myrrlyn** [comment]
I've ultimately decided that you are correct. The `0.16` release will switch to a `Local` cursor and a `Word` fundamental, which are aliased to the target machine's endianness and CPU word size. I cannot give a release date at this time, as `0.16` is bundling a *lot* of refinement work.

I'm going to mark this issue as closed in the commit to master that adds those aliases, and I will comment again when it reaches [crates.io](https://crates.io).
