### ISSUE TITLE
Retrieving a byte vector from BitSlice

### ISSUE THREAD

**Issue by ivan-brko** [myrrlyn/bitvec#27]
Hi, 
Sorry if this question is answered somewhere in the documentation, I checked and couldn't find it.

Is there a way to convert a BitSlice to Vec of u8? And if so, how is the padding handled if the number of bits is not multiple of 8?

**Comment by myrrlyn** [comment]
There is, but it's not a direct path and so doesn't show up in the BitSlice docs.

Clone the BitSlice to a BitVec with .to_owned(), then call .into_vec() on the BitVec to get a plain Vec<T>. Dead bits in the slice edges are left as they are, but I could probably make the library erase them.

In the current master branch and upcoming 0.16 release, BitVecs can have padding on both edges, so you will want to call .force_align() on the BitVec before consuming it.

Also on current master and upcoming 0.16 is the ability to copy a BitSlice directly into an array on the stack. This requires picking a size at compile-time, so it's not suited for dynamic slices, but it does avoid the issue of padding at the front edge. Calling .as_native::<StackType>() on a BitSlice will copy directly into a stack array.

```rust
let bits = some_bitslice();
let mut bv = bits.to_owned();
bv.force_align(); // master and 0.16+ only
bv.into_vec()
```

Alexander Payne
Software Engineer, Space Dynamics Laboratory
________________________________

**Comment by ivan-brko** [comment]
Wow, that was fast.
Thanks a lot!
