### ISSUE TITLE
documentation on docs.rs is down

### ISSUE THREAD

**Issue by Escapingbug** [myrrlyn/bitvec#30]
https://docs.rs/crate/bitvec/0.15.2/builds/185691

**Comment by myrrlyn** [comment]
I know; I have absolutely no idea what to do about it. The docs build as part of my CI process and should build locally. I've spoken to the docs.rs team and hope to have some progress on being able to build, or tell if they'll build, when I release `0.16`.

**Comment by myrrlyn** [comment]
I'm personal friends with the `docs.rs` maintainer, so I asked her to rebuild it and she did.
