### ISSUE TITLE
Lack of reverse fonction

### ISSUE THREAD

**Issue by FlyingCanoe** [myrrlyn/bitvec#39]
There is no reverse function on bitvec as there is on std::vec. By a reverse function I mean a operation that actually reverse the order in witch the bit are store in memory. I am currently building a (bad) Huffman coding project using this library and I rand into this issue.

it his possible that there is actuelle technical raison why this is not fisable

Thank in advance

**Comment by myrrlyn** [comment]
Neither `Vec` nor `BitVec` have a `reverse` method. The Rust standard library function [`slice::reverse`](https://doc.rust-lang.org/std/primitive.slice.html#method.reverse`) is implemented at [`BitSlice::reverse`](https://docs.rs/bitvec/0.17.1/bitvec/slice/struct.BitSlice.html#method.reverse).

As a general rule, `bitvec` types mirror the API surface, including location, of their standard-library counterparts. This means that the functions that use the contents of a collection are typically in `BitSlice`, while `BitVec` only needs to add functions that alter the allocation of memory.

If the behavior of this method is insufficient, please let me know what you need it to do differently. Thank you for the issue!

**Comment by FlyingCanoe** [comment]
Could it be mention in the bitvec doc? in the vec documentation there seam to be exposing a method for this ([https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reverse](url)). the mention of this function on vec mislead me to think that if this behaviour was implemented it with be in BitVec::reverse and not slice::reverse

 thank for the help

**Comment by myrrlyn** [comment]
`Vec<T>` is `Deref<[T]>`, and `BitVec<O, T>` is `Deref<BitSlice<O, T>>`; the doc pages for both will list all the methods from their slice type after all their vector inherent methods. You can find [`<BitVec as Deref<BitSlice>>::reverse`](https://docs.rs/bitvec/0.17.1/bitvec/vec/struct.BitVec.html#method.reverse) there as well.

`BitVec` has more methods than `Vec`, and `BitSlice` has a *lot* of methods, so it is very easy to overlook something on this page.
