### ISSUE TITLE
Fix BitVec on Big-Endian Systems

### ISSUE THREAD

**Issue by Alexhuszagh** [myrrlyn/bitvec#43]
**Relevant Code Failing**

```rust
let u16b = u16::from_ne_bytes(0x1234u16.to_le_bytes());
bytes[5 ..][.. 14].store_le(u16b);
assert_eq!(bytes[5 ..][.. 14].load_le::<u16>(), 0x1234u16);
```

**Result**

```bash
---- fields::tests::lsb0 stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `13330`,
 right: `4660`', src/fields.rs:999:3

---- fields::tests::msb0 stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `13330`,
 right: `4660`', src/fields.rs:1073:3
```

On big-endian [PPC](https://travis-ci.org/myrrlyn/bitvec/jobs/641224779?utm_medium=notification&utm_source=github_status), the above code cails, but on little-endian [PPC](https://travis-ci.org/myrrlyn/bitvec/jobs/641224780?utm_medium=notification&utm_source=github_status), it passes.

**Comment by myrrlyn** [comment]
Awesome. I've always been afraid these were subtly incorrect and I just didn't have a machine on which to test them.

**Comment by Alexhuszagh** [comment]
Some further debugging with a lot of printlns shows that it's store_le that's failing:

```rust
println!("0x1234u16.to_le_bytes()={:?}", 0x1234u16.to_le_bytes());
// 0x1234u16.to_le_bytes()=[52, 18]

let u16b = u16::from_ne_bytes(0x1234u16.to_le_bytes());
println!("u16b={:?}", u16b);
// u16b=13330

bytes[..16].store_le(u16b);
println!("bytes[..16]={:?}", bytes[..16]);
// ACTUAL:   bytes[..16]=BitSlice<Lsb0, u8> [01001000, 00101100]
// EXPECTED: bytes[..16]=BitSlice<Lsb0, u8> [00101100, 01001000]
```

Now, I"m not sure if this is a real issue, or faulty assumptions during unittesting, since `to_le_bytes()` properly switches the byteorder of the integer from big-endian to little-endian, and `store_le` properly switches the byteorder again, assuming it's storing a little-endian value.

**Comment by Alexhuszagh** [comment]
The more I look at this, the more I believe this is simply a logic bug in the testing suite. The following works, as expected:

```rust
let u16b = u16::from_ne_bytes(0x1234u16.to_ne_bytes());
bytes[..16].store_le(u16b);
assert_eq!(bytes[..16].load_le::<u16>(), 0x1234u16);
```

**Comment by Alexhuszagh** [comment]
On big-endian, one more issue:

```
let bits: &BitSlice<Local, usize> = bits![1, 0, 1, 1, 0, 1, 0, 0, 1, 0];
println!("bits={:?}", bits);
// bits=BitSlice<Msb0, usize> [0000000000]
```

The bits macro is therefore broken on big-endian architectures.

**Comment by obeah** [comment]
In my case (little-endian) bitvec! makes wrong initialization after 48th bit.
Probably completely different problem, just found this issue while searching for solution.
```rust
let bits = bitvec![0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
                   0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
                   0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
                   0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
                   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                   0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                   0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

println!("{:?}", bits);
// BitVec<Lsb0, usize> [
//    0b0101101100000000110000000011000101011011000000001100000000110001,
//    0b000000,
//]

```

**Comment by myrrlyn** [comment]
Thank you @obeah for this issue report.

The behavior is now fixed on trunk. I will cherry-pick it down into a `0.17.3` patch release later today or this week.
