### ISSUE TITLE
Doc mentions that bitvec is a newtype wrapper, when it is not

### ISSUE THREAD

**Issue by Purpzie** [myrrlyn/bitvec#53]
https://github.com/myrrlyn/bitvec/blob/83170a4c1c9537aa61cdd906d1ad92e7ecfd2f1b/src/vec.rs#L38
https://github.com/myrrlyn/bitvec/blob/83170a4c1c9537aa61cdd906d1ad92e7ecfd2f1b/src/vec.rs#L250-L261

Shouldn't the doc comment be changed?
(I'm quite new to rust, I'd make a PR but it's probably smart if I don't go that far yet just in case I missed something).

**Comment by myrrlyn** [comment]
That line was last modified when `BitVec` *was* a wrapper over `Vec`. I'll remove it; thanks for reminding me of its existence!

The docs in general are pretty stale; I need to do a documentation pass and bring them all up to the current standard library and `bitvec` implementation.

**Comment by myrrlyn** [comment]
Current `develop` has rewritten these docs. Thank you for the reminder!
