### ISSUE TITLE
How to convert BitSlice to u8?

### ISSUE THREAD

**Issue by hgad** [myrrlyn/bitvec#64]
*Disclaimer: I'm new to BitVec & to Rust*

Is there a way to convert an 8-bit (or less) BitSlice to a u8 without resorting to unsafe Rust (i.e. pointers)?

**Comment by sharksforarms** [comment]
Some simple examples:

```rust
use bitvec::prelude::*;

fn main() {

    let data = [0xAAu8, 0xBB].as_ref();
    let bv = BitVec::<Msb0, u8>::from_slice(data);
    println!("BitVec: {:?}", bv);
    println!("u8 slice: {:x?}", bv.as_slice());

    let bs = bv.as_bitslice();
    println!("BitSlice: {:?}", bs);
    println!("u8 slice: {:x?}", bs.as_slice());

    let bs = &bs[..8];
    println!("BitSlice: {:?}", bs);
    println!("u8 slice: {:x?}", bs.as_slice());
}

/*
BitVec: BitVec<Msb0, u8> [10101010, 10111011]
BitSlice: BitSlice<Msb0, u8> [10101010, 10111011]
BitSlice: BitSlice<Msb0, u8> [10101010]
u8 slice: [aa]
*/
```

**Comment by myrrlyn** [comment]
Another very easy way to perform this is to use the `BitField` trait (in the crate prelude, and available on all collections using `Msb0` or `Lsb0`:

```rust
let bits = bits![Msb0, u8; 0, 1, 0, 1, 0, 0, 1, 1];
let middle = bits[1 .. 7].load::<u8>();
assert_eq!(middle, 0b00101001u8);
```

In general, the types in `bitvec` are designed to be removed and go back to ordinary data very easily. The `.domain()` method on `BitSlice` will also remove the bit-level views and go back to ordinary memory; its behavior is limited only by the fact that it has to be aware of multiple accessors to the same memory region. If you are not splitting up slices and distributing them to multiple owning sites in your program, `.domain()` should produce a complete slice `&[u8]` from your `&BitSlice<_, u8>`.

I will add more documentation explaining how to move between bit views and ordinary memory for the next release.

**Comment by hgad** [comment]
Great, thanks for answering.
