### ISSUE TITLE
Question: Wrinting BitVec values into a file

### ISSUE THREAD

**Issue by andreheringer** [myrrlyn/bitvec#66]
I did not know of a better place to post this question so I'm doing it here. Sorry if I'm not supposed to.

I'm thinking about using BitVec in one of my class projects at university, but I could not find any examples of how can I write the bits in a BitVec into a file. Should I convert the BitVec into another data type before trying to write it? I know the `std::io::write ` function expects an `&[u8]` any tips on how to achieve this would be much helpful.

Anyway beyond that the crate looks really awesome and has helped me gain more experience with Rust (I'm still a noob but getting there).

Stay safe :smile:

**Comment by myrrlyn** [comment]
Use the `BitVec` methods [`.as_slice()`](https://docs.rs/bitvec/latest/bitvec/vec/struct.BitVec.html#method.as_slice) or [`.into_vec()`](https://docs.rs/bitvec/latest/bitvec/vec/struct.BitVec.html#method.into_vec) to produce a view of the underlying memory elements. If you use `BitVec<_, u8>`, then it will be bytes ready to pass into the `Write` trait.

In addition, current `develop` implements `Read` on `BitSlice` for any type parameters. However, using this implementation may cause unexpected memory behavior, and should probably be avoided.

Please feel free to continue to ask questions about usage here, or by reaching me personally through any of the methods listed in the CONTRIBUTING document.
