### ISSUE TITLE
Convert between `BitVec`s of different BitStore types

### ISSUE THREAD

**Issue by fbeutel** [myrrlyn/bitvec#78]
Is there an efficient way of converting between `BitVec`s with different underlying storage types?

This may be especially relevant when reading from or writing to files, which typically yield `u8` data structures, but for performance or serialization reasons it might be better to hold them with a different `BitStore` internally.

**Comment by myrrlyn** [comment]
Try [`BitSlice::align_to`](https://docs.rs/bitvec/0.19.2/bitvec/slice/struct.BitSlice.html#method.align_to). This is always valid when narrowing the storage type, and will (hopefully) be maximally inclusive when widening the storage type. I am not comfortable declaring the soundness of transmuting `Vec<u64>` to `Vec<u8>` even if the buffer size is properly adjusted.

If you are concerned specifically with integration with `std::io` protocols, note that all `BitSlice` and `BitVec`s are `io::Read` and `io::Write`. You may be able to use `io::copy(&mut File, &mut BitVec)` to fill a vector of any storage with reasonable performance.

**Comment by myrrlyn** [comment]
I'm going to close this as inactive, under the assumption that you've figured out your question. If it stands, please re&ouml;pen and I'll be happy to work further.
