### ISSUE TITLE
Bitwise subset

### ISSUE THREAD

**Issue by gahag** [myrrlyn/bitvec#80]
Is it possible to have a subset check (i.e. `(a & b) == a`) for two bitslices with no additional allocation using the current API?

**Comment by gahag** [comment]
Does this produce efficient code? If not, would a pull request implementing such API efficiently be welcome?

**Comment by myrrlyn** [comment]
The compiler is generally pretty good about optimizing these accesses, but it is still a loop iteration per bit.

You can get faster behavior with

```rust
fn fast_subset<O, T>(a: &BitSlice<O, T>, b: &BitSlice<O, T>) -> bool
where O: BitOrder, T: BitStore {
  const W: usize = <usize as bitvec::mem::BitMemory>::BITS as usize;
  a.chunks(W).zip(b.chunks(W)).all(|| {
    let left = a.load::<usize>();
    let right = b.load::<usize>();
    a & b == a
  })
}
```

but it requires that `a` and `b` have the same type parameters. This is probably the case, and likely an easy change if not.

----

It sounds like you want [`.starts_with()`](https://docs.rs/bitvec/0.19.3/bitvec/slice/struct.BitSlice.html#method.starts_with). Right now this is a bitwise crawl, but I can speed it up with the implementation I wrote above.

**Comment by myrrlyn** [comment]
In the next release, all behavior that uses `==` between two slices of the same type parameters (including `.starts_with()`) will use batched loading for accelerated comparison. Slices of different type parameters are not eligible for this acceleration, and will retain their individual-bit iteration behavior.
