### ISSUE TITLE
Implement the BitSet API

### ISSUE THREAD

**Issue by arucil** [myrrlyn/bitvec#83]
The following set operations are what I can think of currently.
```
iter_ones
set difference
collect::<BitSet>() from an iterator of usize's
```

**Comment by myrrlyn** [comment]
The difference between two slices can be computed with the `^` or `^=` operators. At present, these are shims over

```rust
use bitvec::prelude::*;

let a = bits![mut 0, 0, 1, 1];
let b = bits![0, 1, 0, 1];

for (mut a, b) in a.iter_mut().zip(b.iter().copied()) {
  *a ^= b;
}
```

as I have not yet implemented specialization for batch comparison.

The `FromIterator<T>` implementation, as well as the `.iter_ones()` and `.iter_zeros()` methods, will be available in the next release.

If you have any other requests, please feel free to re&ouml;pen this issue.
