### ISSUE TITLE
Is there an API for finding the index of first/last bit set/unset?

### ISSUE THREAD

**Issue by changhe3** [myrrlyn/bitvec#88]
I think it would be incredibly slow to use iterator or indexing to do this, since an `usize` store 64 bits and you may naively mask 64 times for just 64 bits.

**Comment by myrrlyn** [comment]
Currently, only `.iter_ones()` and `.iter_zeros()`. This could probably be specialized to use the `{lead,trail}ing_{one,zero}s` methods available on the integers, but I have not put in the effort to specialize them yet.

**Comment by myrrlyn** [comment]
As of 46161f9, `.iter_{one,zero}s().next{,_back}()` are specialized to use batch operation rather than bit-wise crawl. This will be published in `0.20.1` before the end of the year.
