### ISSUE TITLE
Provide a way to construct a BitTail pointing to the end of a BitRegister

### ISSUE THREAD

**Issue by changhe3** [myrrlyn/bitvec#90]
Currently there's no way to use BitIdx::range iterate through `Domain` if it is not an `Enclave`,

**Comment by myrrlyn** [comment]
Embarassing oversight on my part. Thank you for the report. In `0.20.1`, `BitTail` will expose its `ZERO` and `LAST` constants. You may also use `BitIdx::range_all().skip(head.value() as usize)` to create the same iterator.
