### ISSUE TITLE
please include LICENSE.txt in the sources uploaded to crates.io

### ISSUE THREAD

**Issue by decathorpe** [myrrlyn/bitvec#93]
There exist more than 20 variants of *the* "MIT" license.

Side note: Unless I did my comparison wrong, you seem to have chosen the "Modern Style with sublicense", as it is classified by the Fedora project: https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_sublicense

Your LICENSE.txt text states:

> The above copyright notice and this permission notice shall be included
> in all copies or substantial portions of the Software.

So, to clarify which "MIT" license actually applies, and to adhere to the text of the chosen license, please include the LICENSE.txt file with the crate published to crates.io. Adding a "LICENSE.txt" entry to the "include" array in Cargo.toml should do that.

**Comment by myrrlyn** [comment]
I did not know the MIT had fragmented like that.

I have been sidelining a more thorough license research while I mull over whether to remain on MIT as I approach a full relesae. Regardless, you are correct that I should include whichever license I am using in the distribution.

The repository license file will be included in all published versions, beginning with `0.20.1`.

**Comment by decathorpe** [comment]
Thank you!
