### ISSUE TITLE
Possible BitArray serialization bug

### ISSUE THREAD

**Issue by 1024bees** [myrrlyn/bitvec#96]
Hey Folks,

It seems that there is a possible serialization bug with BitArray when using [bincode](https://docs.rs/bincode/1.3.1/bincode/). This error manifests  with the following test: 

```
#[cfg(test)]
mod tests {
    use bincode;
    use bitvec::prelude::*;

    #[test]
    fn serialize_bitarr_bincode() {
        let ba = bitarr![Msb0, u8; 1, 1, 1, 1, 1, 0, 0, 0];

        let bytes = bincode::serialize(&ba).expect("bincode serialization failed");

        let deser = bincode::deserialize::<BitArray<Msb0,[u8; 1]>>(bytes.as_ref()).expect("bincode deserialization failed");
        
        assert_eq!(deser,ba);
    }
}
```

The underlying issue seems to be that on the serialization end, we are serializing a &[u8] slice, but on the de-serialization end, we are expecting to de-serialize a serialized [u8; 1] array.  

It looks like Bincode serializes slices and fixed size arrays differently:

- Slices are serialized by having a length byte followed by some fixed length payload (in this case the payload is 9 bytes long. this is tuneable )

- Serializing arrays looks to be a memcpy.

This bug doesn't manifest with with serde_json, and I haven't tried any other serde serialization "targets". The larger problem this potential bug presents is that structs that contain BitArr's and that use derived Serde traits cannot be serialized or deserialized with bincode.

FWIW, my current work around is to clone the bitarr that is being serialized and then unwrap it: 
`let bytes = bincode::serialize(&ba.clone().unwrap()).unwrap()`

I'd be glad to look into this if you'd have any thoughts on where it should be addressed (on the bitvec side, bincode side, etc).

**Comment by myrrlyn** [comment]
Thank you for this report! I had not tested any transport formats; only the abstract `serde` token stream.

This fix will be published in `0.20.1` later this week.

As noted in the commit, I reserve the right to change the `BitArray` implementation of the `serde` interface, and am not committing to a stable transport format. *However*, such a change will be considered semver breaking. I expect to change the implementation only when I am able to replace the current `BitArray` with a const-generic type, which will constitute a much larger breaking change *anyway*.

Thank you again for this report.
